<?php 
$catId = $this->getRequest()->getParam('id');
?>
	<?php $catId = Mage::app()->getRequest()->getParam('catid'); ?>	
		<?php			
				$manufacturers = $this->getManufacturers();
				if(count($manufacturers)):
					$i = 0;
					$column = Mage::helper('manufacturer')->getNumberColumn();
		?>
			<div class="block block-subscribe">
				<div class="block-title"><strong><span><?php echo $this->__('Brands'); ?></strong></span></div>
				<div class="block-content">
					<div id="manufacturer-table">
						<table id="listmanufacturer">
							<?php	
															
								foreach($manufacturers as $manufacturer):
								$numberProduct = count(Mage::getModel('manufacturer/manufacturer')->addFilters($catId, $manufacturer->getId()));
									if($i % $column == 0):
							?>
									<tr>
								<?php endif; ?>
								
								<?php if(!Mage::helper('manufacturer')->displayManufacturerHasNoProduct()): ?>
									<?php if($numberProduct): ?>
										<td><a href="<?php echo $this->getManufacturerDetailUrl($manufacturer); ?>" title="<?php echo $manufacturer->getName(); ?>"><span><?php echo $manufacturer->getData('name_store'); ?></span></a>
										<?php if(Mage::helper('manufacturer')->isDisplayNumberProduct()): ?>
											(<?php echo $numberProduct; ?>)
										<?php endif; ?>
										</td>
									<?php $i++; endif; ?>
								<?php else: ?>
										<td><a href="<?php echo $this->getManufacturerDetailUrl($manufacturer); ?>" title="<?php echo $manufacturer->getName(); ?>"><span><?php echo $manufacturer->getData('name_store'); ?></span></a>
										<?php if(Mage::helper('manufacturer')->isDisplayNumberProduct()): ?>
											(<?php echo $numberProduct; ?>)
										<?php endif; ?>
										</td>
									<?php $i++; ?>
								<?php endif; ?>
								<?php if($i % $column == 0): ?>
									</tr>
								<?php endif; ?>
							<?php endforeach; ?>
						</table>
					</div>
				</div>
			</div>
				<?php endif; ?>
			
			<script type="text/javascript">
				decorateTable('listmanufacturer');
			</script>		
