<?php
$most_frequently = $this->getMostFrequently();
$categories = $this->getAllCategory();
$overview_number = Mage::getStoreConfig('faq/general/overview_number');
?>

<div class="faq">
<div class="page-title"><h2><?php echo($this->__("Most Frequently Asked Questions")); ?></h2></div>
<div  id="most_frequently">
<ul>
<?php 
	$count = 0;
	foreach($most_frequently as $question)
	{
		$count++;
		echo("<li> ".$count . ". <a href='". Mage::getBaseUrl() . $question->getUrlKey() ."' title='".$question->getTitle()."'>".$question->getTitle()."</a> </li>");
	}
?>

</ul>
</div>
<form method="get" action="<?php echo(Mage::getBaseUrl() . "faq/search/result/"); ?>" name="faqsearch">
<div id="searchform">
	<label for="keyword"><?php echo $this->__('Search FAQ') ?></label><input type="text" name="keyword" id="keyword" size="30" maxlength="30" onfocus="this.value='';"/>
	<button type="button" id="btnSearchFaq" onclick="javascript:faq_search();" title="<?php echo $this->__('Search FAQ') ?>" class="button" value="<?php echo $this->__('Search FAQ') ?>"><span><span><?php echo $this->__('Search FAQ') ?></span></span></button>	
</div>
</form>

<h1><?php echo($this->__("FAQ Topics"));?></h1>

<div id="list_category" class="clearfix">
<ul>
	<?php 
	if(count($categories))
	{
		$cat_count = 0;
		foreach($categories as $category)
		{
			if($cat_count % 2 ==0)
			{			
				echo("<li class='left'>");
			}
			else
			{
				echo("<li class='right'>");
			}
			$cat_count = $cat_count + 1;
			
			
				echo("<h3>".$category->getName()."</h3>");
				
				$questions = Mage::getModel("faq/faq")
									->setStoreId($this->getStoreId())
									->getQuestions($category->getCategoryId(),$overview_number);
				if(count($questions))
				{
					$index = 1;
					
					foreach($questions as $question)
					{
						echo("<div>");
						echo($index . ". <a href='". Mage::getBaseUrl() . $question->getUrlKey() ."'>". $question->getTitle() . "</a><br/>" );
						$index++;
						echo ("</div>");
					}
					echo("<div>");
					echo("<a class='more' href='". Mage::getBaseUrl(). $category->getUrlKey() . "' title='". $this->__("more") . "'>". $this->__("more") . "</a>");
					echo("</div>");
					
				}
			echo("</li>");
		}
	}
	?>
</ul>
</div>

<br><br>
</div>