<?php
	if(Mage::registry("questions"))
	{
		$questions = Mage::registry("questions");
		$keywords = Mage::registry("keywords");		
?>
<div class="faq clearfix">
	<div class="page-title">
		<h2><?php echo($this->__("Search FAQ"));?></h2>
	</div>
	<form method="get" action="<?php echo(Mage::getBaseUrl() . "faq/search/result/"); ?>" name="faqsearch" id="faqsearch">
	<div id="searchform">
		<label for="keyword"><?php echo $this->__('Search FAQ') ?></label><input type="text" name="keyword" id="keyword" size="30" maxlength="30" onfocus="this.value='';"/>
	<button type="button" id="btnSearchFaq" onclick="javascript:faq_search();" title="<?php echo $this->__('Search FAQ') ?>" class="button" value="<?php echo $this->__('Search FAQ') ?>"><span><span><?php echo $this->__('Search FAQ') ?></span></span></button>	
	</div>
	</form>
	
	<h3><?php echo $this->__('FAQ Search Results');?></h3>
	<span><?php echo($this->__('Keywords') . ': "' . $keywords . '" ('. count($questions).' '.$this->__("Matches").')</span>'); ?>
	<br><br>
	<?php
		if(count($questions))
		foreach($questions as $question)
		{			
			echo("<div class='faq_view'>");								
			echo("<strong>".$question->getTitle()."</strong></br>");
			echo("<div class='faq_conent'>". $question->getDescription()."</div>");
			echo("</div>");
		}
	?>
	
</div>
<?php		
	}
?>