<?php 
$mode = $this->getShownType();
$delay_time = $this->getDelayTime();
?>
<?php if (($products = $this->getProductCollection())): ?>
	<div class="title-list">
		<h5><?php echo $this->__('Featured Product')?></h5>
	</div>
	<?php $_collectionSize = $products->count() ?>
    <?php $_columnCount = 3; ?>
	<div id="featuredproduct-list">
		<?php $k=0;?>
		<?php $i = 0; foreach ($products->getItems() as $_product): ?>
			<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid">
			<?php endif ?>	
				<li class="item<?php echo $k++;?><?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<?php $thumb_size = getThumbSize($_product->getSmallImage(),211, 196) ?>
				<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_size['width'],$thumb_size['height'])->keepFrame(false); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
					
						<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>&nbsp;
						<?php endif; ?>
					
					<div class="price-cart">
					   <?php echo $this->getPriceHtml($_product, true) ?>
						<div class="actions">
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						   
						</div>
					</div>
				</li>			
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
			<?php endif ?>	
		<?php endforeach;?>
	</div>
<?php endif; ?>
<script type="text/javascript">
  var $j = jQuery.noConflict();
        //$j(document).ready(function() {

function delayrow(){
         var maxHeight = 0;  var maxLi = 0;  

		  $j('ul.products-grid').each(function(){

					maxHeight = $j(this).find('li.item0 h2.product-name').height();

					if(maxHeight < $j(this).find('li.item1 h2.product-name').height())
					{
						maxHeight = $j(this).find('li.item1 h2.product-name').height();
					}
					
					if(maxHeight < $j(this).find('li.item2 h2.product-name').height())
					{
						maxHeight = $j(this).find('li.item2 h2.product-name').height();
					}
					maxHieghtnew = maxHeight+'px';
					$j(this).find('li.item0 h2.product-name').css('height',maxHeight);
					$j(this).find('li.item1 h2.product-name').css('height',maxHeight);
					$j(this).find('li.item2 h2.product-name').css('height',maxHeight);
					
					maxLi = $j(this).find('li.item0').height();

					if(maxLi < $j(this).find('li.item1').height())
					{
						maxLi = $j(this).find('li.item1').height();
					}
					
					if(maxLi < $j(this).find('li.item2').height())
					{
						maxLi = $j(this).find('li.item2').height();
					}
					maxLinew = maxLi+'px';
					$j(this).find('li.item0').css('height',maxLinew);
					$j(this).find('li.item1').css('height',maxLinew);
					$j(this).find('li.item2').css('height',maxLinew);
			  
			
		   });
		   
}

setTimeout("delayrow()", 1000);
        //});
</script> 
<?php
function getThumbSize($image_file,$width,$height)
{
	$image_path = Mage::getBaseDir('media').DS.'catalog'.DS.'product'.$image_file;
	if(file_exists($image_path)){
		$image = new Varien_Image($image_path);
		$org_width = $image->getOriginalWidth();
		$org_height = $image->getOriginalHeight();
		if($org_width / $org_height < $width/$height){
			$thumb_width = $width;
			$thumb_height = (int) ($org_height * $thumb_width / $org_width) +1 ;
		} else {
			$thumb_height = $height;
			$thumb_width = (int) ($org_width * $thumb_height / $org_height) +1 ;		
		}
	} else {
		$thumb_width = $width;
		$thumb_height = $height;		
	}
	return array('width' => $thumb_width, 'height' => $thumb_height);
}
?>	