<?php
/**
 * @see Magestore_Themeinstaller_Block_Adminhtml_Wizardinstaller
 */
?>
<?php $cms_pages = $this->getCmsPages()?>
<div class="message">
	<div class="title"><?php echo $this->__('Do you want to create the cms pages below?') ?></div>
	<div class="cms-page-install">
		<?php if(count($cms_pages) ): ?>
			<?php $i=0 ?>
			<ul>
			<?php foreach($cms_pages as $cms_page): ?>
				<?php $i++ ?>
				<li>
					<span class="label"><label><?php echo $i ?>. <?php echo $cms_page['title'] ?></label></span>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		<div class="content-option-installer">
			<ul>
				<li>
					<input type="radio" value="1" id="is_install_theme_yes" class="radio validate-one-required-by-name" name="is_install_theme" onclick="themeInstaller.showHomepageConfig('themeinstaller_homepage_setting','is_use_homepage');" checked>
					<span class="label"><label for="is_install_theme_yes"><?php echo $this->__('Yes') ?></label></span>
				</li>
				<li>
					<input type="radio" value="0" id="is_install_theme_no" class="radio validate-one-required-by-name" name="is_install_theme" onclick="themeInstaller.hideHomepageConfig('themeinstaller_homepage_setting','is_use_homepage');">
					<span class="label"><label for="is_install_theme_no"><?php echo $this->__('No') ?></label></span>
				</li>			
			</ul>	
		</div>
		<br/>
		<div id="themeinstaller_homepage_setting" class="content-option-installer">
			<div class="title"><?php echo $this->__('Do you want to use the Home page of this theme?') ?></div>
			<ul>
				<li>
					<input type="checkbox" id="is_use_homepage" class="" name="is_use_homepage" checked>
					<span class="label"><label for="is_use_homepage"><?php echo $this->__('Yes, I want to use it.') ?></label></span>
				</li>		
			</ul>		
		</div>
		<input type="hidden" name="run_installer" value="1" />	
		<input type="hidden" name="selected_theme" value="<?php echo $this->getSelectedTheme() ?>" />	
	</div>
</div>
<div class="buttons">
	<button type="button" class="themeinstaller-back button" onclick="themeInstaller.back();">
		<span>
			<span><?php echo $this->__('Back')?></span>
		</span>
	</button>
	<button type="button" class="themeinstaller-cancel button btn-sparator" onclick="themeInstaller.cancel();">
		<span>
			<span><?php echo $this->__('Cancel')?></span>
		</span>
	</button>	
	<button type="button" class="themeinstaller-accept button" onclick="themeInstaller.run();">
		<span>
			<span><?php echo $this->__('Next')?></span>
		</span>
	</button>			
</div>