<?php
/**
 * @see Magestore_Themeinstaller_Block_Adminhtml_Wizardinstaller
 */
?>

<div class="message">
	<div class="title">
		<?php echo $this->getThemeInstallMessage() ?> 
	</div>
</div>
<input type="hidden" name="is_install" value="1"/>
<div class="buttons">
<!--
	<button type="button" class="themeinstaller-back button">
		<span>
			<span><?php echo $this->__('Back')?></span>
		</span>
	</button>
-->	
	<button type="button" class="themeinstaller-cancel button" onclick="themeInstaller.cancel();">
		<span>
			<span><?php echo $this->__('Cancel')?></span>
		</span>
	</button>	
	<button type="button" class="themeinstaller-accept button" onclick="themeInstaller.run();">
		<span>
			<span><?php echo $this->__('Next')?></span>
		</span>
	</button>			
</div>