<?php
$ajax_cart		 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
$image_product_hover 	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
$quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
$thumb_width =  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
$thumb_height = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
$cat_ids = explode(",",$this->getCateoryID());
foreach ($cat_ids as $cat_id) {
//echo $this->getCategoryName($cat_id);
}
?>
		<div class="row-fluid home-list-title">
			<div class="span5 title-left">
				<h2 class="title"><?php echo $this->getBlockTitle() ?></h2>
			</div>
			<div class="span7 title-left">
				<div class="filter-nav">
					<ul id="filters" class="option-set clearfix" data-option-key="filter">
						<li><a class="" data-filter="*" href="#filter">show all</a></li>
						<?php
						foreach ($cat_ids as $cat_id) {
						if($cat_id == $this->getSelected()){
							$selected = 'class="selected"';
						}else{
							$selected = '';
						}
						echo '<li><a data-filter=".filter-cat-'.$cat_id.'" href="#filter" '.$selected.'>'.$this->getCategoryName($cat_id).'</a></li>';
						}
						?>
				    </ul>
				</div>
			</div>
		</div>
		<div class="row-fluid products-filter products-grid">	
		 		<ul id="container-filter" class="products-grid">
						<?php
						foreach ($cat_ids as $cat_id):
							$_products = $this->getProductList($cat_id);
						?>
						
				 	<?php $i=0; foreach ($_products->getItems() as $_product): ?>
				       	<li class="item filter-cat-<?php echo $cat_id?>">
							<div class="nova-product-images"> 
								<?php include('labels.phtml')  ?> 
								<?php if($quick_view): ?>
								<div class="quickview-box">
									<a class="quickview_small" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>">Quick View</a> 
								</div>
								<?php endif;?>
					            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					                          <?php 
					                if($image_product_hover) { ?>
					                <div class="front margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
					                <?php
					                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
					                 foreach ($_gallery as $_image ):
					                 ?>
					                 <div class="product-img-additional back margin-image">
					                 <img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
					                 </div>
					                 <?php
											break;
											endforeach;
									?>
									<?php
									}else{
									?>
									 <div class="margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									 </div>
									<?php	
									}
									?>	
									<span class="theHoverBorder"></span>		               
					        	</a>
								
							</div>
				        	<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
				        	<div class="price-product-box">
				            	<?php echo $this->getPriceHtml($_product, true) ?>
				            	<div class="descriptions-hidden">		
									<div class="quick-act" id="quick-act-<?php echo $_product->getId()?>">            
										<?php if($ajax_cart):?> 	
										<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
									 	<a rel="tooltip" class="add_to_cart_small" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><i class="icon-basket-1"></i></i></a> 
										<?php else:?>		
									  	<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><i class="icon-basket-1"></i></a> 
									 	<?php endif; ?> 
										<?php else:?>
									 	<a rel="tooltip" class="add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><i class="icon-basket-1"></i></a> 
										<?php endif; ?> 
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
									 	<a title="Wishlist" class="add_to_wishlist_small" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="icon-wishlist"></i></a> 
										<?php endif; ?> 
									 	<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									 	<a title="Compare" class="add_to_compare_small" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="icon-chart-bar-1"></i></a> 
										<?php endif; ?>
									</div>
								</div>
				        	</div>
				            <div class="rating-product-box">
				            	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							</div>
				            <div class="clear"></div>	
				            	
				        </li>
				    	<?php endforeach; ?>
				    	<?php endforeach; ?>
				 </ul>

		</div>		
  	
  <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>novaworks/jquery.isotope.min.js"></script>
 <script type="text/javascript"> 
		jQuery(window).load(function(){ 
			// cache container
			var $container = jQuery('#container-filter');
			$default = jQuery('#filters').find('.selected').attr('data-filter'); 
			// filter items when filter link is clicked
			$container.isotope({ 
			  	itemSelector : '.item',
			  	filter: $default
			 });
			jQuery('#filters a').click(function(){
			  var selector = jQuery(this).attr('data-filter');
			  jQuery(this).parents('#filters').find('.selected').removeClass('selected');
	          jQuery(this).addClass('selected');
			  $container.isotope({ 
			  	itemSelector : '.item',
			  	filter: selector
			  });
			  return false;
			});
	
		});
	</script>	